/**
 * Furniture Catalog Database
 * 
 * Comprehensive catalog with detailed pricing, materials, dimensions,
 * and buy links from IKEA, Pepperfry, and Urban Ladder.
 */

const FURNITURE_CATALOG = {
    sofa: {
        label: 'Modern Sofa',
        icon: '🛋️',
        category: 'Living Room',
        description: 'Elegant 3-seater sofa with premium upholstery, high-density foam cushions, and solid wood frame for lasting comfort.',
        dimensions: { width: '200 cm', depth: '85 cm', height: '82 cm' },
        weight: '45 kg',
        warranty: '5 Years Structural Warranty',
        rating: 4.5,
        reviews: 2340,
        materials: [
            { name: 'Frame', detail: 'Solid Sheesham Wood (Kiln-dried)' },
            { name: 'Upholstery', detail: 'Premium Fabric (Polyester Blend)' },
            { name: 'Cushion', detail: 'High Density HR Foam (40D)' },
            { name: 'Legs', detail: 'Solid Wood with Walnut Finish' },
            { name: 'Suspension', detail: 'Sinuous Springs + Webbing' },
        ],
        priceRange: { min: 25000, max: 65000 },
        variants: [
            { name: 'Fabric - Grey', price: 32000, color: '#808080' },
            { name: 'Fabric - Navy', price: 32000, color: '#1e3a5f' },
            { name: 'Leatherette - Brown', price: 45000, color: '#5c3a1e' },
            { name: 'Velvet - Emerald', price: 55000, color: '#2e6b4f' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'KIVIK 3-Seat Sofa',
                price: '₹41,990',
                url: 'https://www.ikea.com/in/en/p/kivik-3-seat-sofa-tibbleby-beige-s69440571/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Jerrish 3 Seater Sofa',
                price: '₹28,499',
                url: 'https://www.pepperfry.com/category/sofas.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Marzano Sofa Set',
                price: '₹35,999',
                url: 'https://www.urbanladder.com/sofas',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Living Room', 'Seating', 'Comfort', '3-Seater'],
    },

    armchair: {
        label: 'Armchair',
        icon: '🪑',
        category: 'Living Room',
        description: 'Plush single-seater armchair with ergonomic design and premium cushioning for ultimate relaxation.',
        dimensions: { width: '75 cm', depth: '80 cm', height: '85 cm' },
        weight: '18 kg',
        warranty: '3 Years Warranty',
        rating: 4.3,
        reviews: 890,
        materials: [
            { name: 'Frame', detail: 'Engineered Wood + Metal Inner' },
            { name: 'Upholstery', detail: 'Linen Fabric / Cotton Blend' },
            { name: 'Cushion', detail: 'Memory Foam (35D)' },
            { name: 'Legs', detail: 'Powder-Coated Metal' },
        ],
        priceRange: { min: 8000, max: 25000 },
        variants: [
            { name: 'Fabric - Beige', price: 12000, color: '#d4b896' },
            { name: 'Fabric - Blue', price: 12000, color: '#4a6fa5' },
            { name: 'Velvet - Mustard', price: 18000, color: '#c49a2a' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'STRANDMON Wing Chair',
                price: '₹17,990',
                url: 'https://www.ikea.com/in/en/cat/armchairs-chaise-longues-fu003/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Tampa Accent Chair',
                price: '₹11,999',
                url: 'https://www.pepperfry.com/category/accent-chairs.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Hagen Lounge Chair',
                price: '₹14,499',
                url: 'https://www.urbanladder.com/lounge-chairs',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Living Room', 'Seating', 'Accent'],
    },

    coffeeTable: {
        label: 'Coffee Table',
        icon: '☕',
        category: 'Living Room',
        description: 'Sleek contemporary coffee table with tempered glass top and brushed metal legs, perfect centerpiece for modern living.',
        dimensions: { width: '110 cm', depth: '55 cm', height: '45 cm' },
        weight: '22 kg',
        warranty: '2 Years Warranty',
        rating: 4.4,
        reviews: 1560,
        materials: [
            { name: 'Top', detail: '12mm Tempered Glass / Engineered Wood' },
            { name: 'Frame', detail: 'Powder-Coated Iron / Solid Wood' },
            { name: 'Finish', detail: 'Matte Black / Walnut PU' },
            { name: 'Base', detail: 'Anti-Scratch Rubber Pads' },
        ],
        priceRange: { min: 5000, max: 18000 },
        variants: [
            { name: 'Glass + Metal', price: 8500, color: '#333' },
            { name: 'Marble Top', price: 15000, color: '#e8e0d8' },
            { name: 'Wood - Walnut', price: 10000, color: '#5c3a1e' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'LACK Coffee Table',
                price: '₹2,990',
                url: 'https://www.ikea.com/in/en/cat/coffee-side-tables-10705/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Wayne Coffee Table',
                price: '₹7,499',
                url: 'https://www.pepperfry.com/category/coffee-tables.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Tate Coffee Table',
                price: '₹9,999',
                url: 'https://www.urbanladder.com/coffee-tables',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Living Room', 'Table', 'Glass'],
    },

    tvUnit: {
        label: 'TV Unit',
        icon: '📺',
        category: 'Living Room',
        description: 'Modern wall-mounted TV unit with cable management, ample storage, and LED strip provision for ambient lighting.',
        dimensions: { width: '180 cm', depth: '40 cm', height: '55 cm' },
        weight: '35 kg',
        warranty: '3 Years Warranty',
        rating: 4.6,
        reviews: 1120,
        materials: [
            { name: 'Body', detail: 'Engineered Wood (E1 Grade MDF)' },
            { name: 'Finish', detail: 'PU Laminate / Wood Veneer' },
            { name: 'Handles', detail: 'Brushed Aluminium' },
            { name: 'Hinges', detail: 'Soft-Close Hettich Hinges' },
        ],
        priceRange: { min: 10000, max: 35000 },
        variants: [
            { name: 'Walnut Finish', price: 18000, color: '#5c3a1e' },
            { name: 'White + Oak', price: 20000, color: '#f5f0e8' },
            { name: 'Dark Wenge', price: 16000, color: '#2c1a0e' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'BESTÅ TV Bench',
                price: '₹11,990',
                url: 'https://www.ikea.com/in/en/cat/tv-media-furniture-10475/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Astrid TV Unit',
                price: '₹12,999',
                url: 'https://www.pepperfry.com/category/tv-units.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Hayden TV Unit',
                price: '₹16,499',
                url: 'https://www.urbanladder.com/tv-units',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Living Room', 'Entertainment', 'Storage'],
    },

    bedKing: {
        label: 'King Size Bed',
        icon: '🛏️',
        category: 'Bedroom',
        description: 'Luxurious King-size bed with upholstered headboard, solid wood construction, and under-bed storage drawers.',
        dimensions: { width: '198 cm', depth: '213 cm', height: '110 cm' },
        weight: '85 kg',
        warranty: '10 Years Structural Warranty',
        rating: 4.7,
        reviews: 3450,
        materials: [
            { name: 'Frame', detail: 'Solid Sheesham / Teak Wood' },
            { name: 'Headboard', detail: 'Upholstered Fabric / Leatherette' },
            { name: 'Slats', detail: 'Plywood Slats (18mm)' },
            { name: 'Storage', detail: 'Hydraulic Lift / Drawer Mechanism' },
            { name: 'Finish', detail: 'Premium PU Polish' },
        ],
        priceRange: { min: 30000, max: 95000 },
        variants: [
            { name: 'Honey Finish', price: 42000, color: '#c49a2a' },
            { name: 'Dark Walnut', price: 48000, color: '#3a2010' },
            { name: 'White + Oak', price: 55000, color: '#f0ebe0' },
            { name: 'Upholstered Grey', price: 65000, color: '#808080' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'MALM Bed Frame (King)',
                price: '₹24,990',
                url: 'https://www.ikea.com/in/en/cat/double-beds-16284/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Arisa King Bed',
                price: '₹32,999',
                url: 'https://www.pepperfry.com/category/king-size-beds.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Valencia King Bed',
                price: '₹44,999',
                url: 'https://www.urbanladder.com/king-size-beds',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Bedroom', 'King Size', 'Storage'],
    },

    bedSingle: {
        label: 'Single Bed',
        icon: '🛏️',
        category: 'Bedroom',
        description: 'Compact single bed ideal for kids or guest rooms, with durable construction and optional trundle.',
        dimensions: { width: '100 cm', depth: '200 cm', height: '90 cm' },
        weight: '40 kg',
        warranty: '5 Years Warranty',
        rating: 4.4,
        reviews: 980,
        materials: [
            { name: 'Frame', detail: 'Solid Pine Wood / Engineered Wood' },
            { name: 'Slats', detail: 'Bentwood Slats' },
            { name: 'Finish', detail: 'Water-Based Lacquer' },
        ],
        priceRange: { min: 10000, max: 30000 },
        variants: [
            { name: 'Natural Pine', price: 12000, color: '#d4a76a' },
            { name: 'White Finish', price: 14000, color: '#f0f0f0' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'SUNDVIK Bed Frame',
                price: '₹11,990',
                url: 'https://www.ikea.com/in/en/cat/single-beds-16285/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'McBeth Single Bed',
                price: '₹14,999',
                url: 'https://www.pepperfry.com/category/single-beds.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Yorktown Single Bed',
                price: '₹18,499',
                url: 'https://www.urbanladder.com/single-beds',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Bedroom', 'Single', 'Compact'],
    },

    wardrobe: {
        label: 'Wardrobe',
        icon: '🚪',
        category: 'Bedroom',
        description: '2-door wardrobe with full-length mirror, multiple shelves, hanging rod, and soft-close doors.',
        dimensions: { width: '120 cm', depth: '55 cm', height: '210 cm' },
        weight: '65 kg',
        warranty: '5 Years Warranty',
        rating: 4.5,
        reviews: 2010,
        materials: [
            { name: 'Body', detail: 'Plywood (BWP Grade 710)' },
            { name: 'Doors', detail: 'MDF with PU Finish' },
            { name: 'Interior', detail: 'Pre-Laminated Particle Board' },
            { name: 'Hinges', detail: 'Hettich Soft-Close Hinges' },
            { name: 'Handles', detail: 'Stainless Steel Profile Handle' },
        ],
        priceRange: { min: 20000, max: 75000 },
        variants: [
            { name: 'Classic Walnut', price: 35000, color: '#5c3a1e' },
            { name: 'White Gloss', price: 42000, color: '#f5f5f5' },
            { name: 'Sliding Door', price: 55000, color: '#333' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'PAX Wardrobe System',
                price: '₹27,990',
                url: 'https://www.ikea.com/in/en/cat/wardrobes-19053/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Okinawa 2 Door Wardrobe',
                price: '₹22,999',
                url: 'https://www.pepperfry.com/category/wardrobes.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Domenico Wardrobe',
                price: '₹39,999',
                url: 'https://www.urbanladder.com/wardrobes',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Bedroom', 'Storage', 'Wardrobe'],
    },

    nightstand: {
        label: 'Nightstand',
        icon: '🗄️',
        category: 'Bedroom',
        description: 'Compact bedside table with drawer and open shelf, perfect for keeping essentials within reach.',
        dimensions: { width: '45 cm', depth: '40 cm', height: '55 cm' },
        weight: '12 kg',
        warranty: '2 Years Warranty',
        rating: 4.2,
        reviews: 650,
        materials: [
            { name: 'Body', detail: 'Solid Mango Wood' },
            { name: 'Drawer', detail: 'Dovetail Joint with Runners' },
            { name: 'Finish', detail: 'Lacquer / PU Finish' },
        ],
        priceRange: { min: 3000, max: 12000 },
        variants: [
            { name: 'Honey Oak', price: 5000, color: '#c49a2a' },
            { name: 'White', price: 4500, color: '#f0f0f0' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'HEMNES Bedside Table',
                price: '₹5,990',
                url: 'https://www.ikea.com/in/en/cat/bedside-tables-20656/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Clancy Bedside Table',
                price: '₹4,299',
                url: 'https://www.pepperfry.com/category/bedside-tables.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Zephyr Nightstand',
                price: '₹6,999',
                url: 'https://www.urbanladder.com/bedside-tables',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Bedroom', 'Bedside', 'Storage'],
    },

    diningTable: {
        label: 'Dining Table',
        icon: '🍽️',
        category: 'Dining',
        description: '6-seater dining table with solid wood top and sturdy metal/wood legs, ideal for family gatherings.',
        dimensions: { width: '150 cm', depth: '90 cm', height: '76 cm' },
        weight: '40 kg',
        warranty: '5 Years Warranty',
        rating: 4.6,
        reviews: 1870,
        materials: [
            { name: 'Top', detail: 'Solid Sheesham / Marble / Glass' },
            { name: 'Legs', detail: 'Solid Wood / Cast Iron' },
            { name: 'Finish', detail: 'Premium PU / Natural Oil' },
            { name: 'Edge', detail: 'Beveled / Live-Edge' },
        ],
        priceRange: { min: 15000, max: 55000 },
        variants: [
            { name: 'Sheesham Natural', price: 22000, color: '#8b5a2b' },
            { name: 'Marble Top', price: 45000, color: '#e8e0d8' },
            { name: 'Glass + Metal', price: 18000, color: '#333' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'EKEDALEN Table',
                price: '₹21,990',
                url: 'https://www.ikea.com/in/en/cat/dining-tables-21825/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Alton 6 Seater Table',
                price: '₹17,999',
                url: 'https://www.pepperfry.com/category/dining-tables.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Arabia Dining Table',
                price: '₹26,999',
                url: 'https://www.urbanladder.com/dining-tables',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Dining', '6-Seater', 'Family'],
    },

    kitchenCabinet: {
        label: 'Kitchen Cabinet',
        icon: '🗄️',
        category: 'Kitchen',
        description: 'Modular kitchen base cabinet with adjustable shelves, soft-close drawer, and moisture-resistant construction.',
        dimensions: { width: '80 cm', depth: '60 cm', height: '85 cm' },
        weight: '28 kg',
        warranty: '10 Years Warranty',
        rating: 4.5,
        reviews: 920,
        materials: [
            { name: 'Body', detail: 'Marine Plywood (BWP 710)' },
            { name: 'Shutter', detail: 'MDF with Acrylic / Membrane' },
            { name: 'Countertop', detail: 'Granite / Quartz (optional)' },
            { name: 'Hardware', detail: 'Hettich / Hafele Fittings' },
            { name: 'Sealant', detail: 'Anti-Moisture Edge Banding' },
        ],
        priceRange: { min: 25000, max: 80000 },
        variants: [
            { name: 'Acrylic White', price: 40000, color: '#f5f5f5' },
            { name: 'Wood Grain', price: 35000, color: '#8b5a2b' },
            { name: 'Matte Grey', price: 45000, color: '#666' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'KNOXHULT Kitchen',
                price: '₹18,990',
                url: 'https://www.ikea.com/in/en/cat/modular-kitchens-ka001/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Marine L-Shape Kitchen',
                price: '₹45,999',
                url: 'https://www.pepperfry.com/category/kitchen-cabinets.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Modular Kitchen Unit',
                price: '₹55,000',
                url: 'https://www.urbanladder.com/modular-kitchens',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Kitchen', 'Modular', 'Storage'],
    },

    fridge: {
        label: 'Refrigerator',
        icon: '❄️',
        category: 'Kitchen',
        description: 'Double-door frost-free refrigerator with convertible modes, energy-efficient compressor, and smart cooling.',
        dimensions: { width: '70 cm', depth: '70 cm', height: '175 cm' },
        weight: '62 kg',
        warranty: '10 Years Compressor Warranty',
        rating: 4.4,
        reviews: 5670,
        materials: [
            { name: 'Body', detail: 'Pre-Painted Steel Sheet' },
            { name: 'Interior', detail: 'ABS Plastic (FDA Approved)' },
            { name: 'Insulation', detail: 'CFC-Free PU Foam' },
            { name: 'Compressor', detail: 'Digital Inverter' },
        ],
        priceRange: { min: 18000, max: 65000 },
        variants: [
            { name: 'Silver', price: 28000, color: '#c0c0c0' },
            { name: 'Black Steel', price: 35000, color: '#333' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'Built-in Fridge Solutions',
                price: '₹Contact',
                url: 'https://www.ikea.com/in/en/cat/fridges-freezers-ka003/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Samsung 253L Fridge',
                price: '₹26,490',
                url: 'https://www.pepperfry.com/category/refrigerators.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'LG 260L Frost Free',
                price: '₹24,990',
                url: 'https://www.urbanladder.com/appliances',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Kitchen', 'Appliance', 'Essential'],
    },

    stove: {
        label: 'Stove / Hob',
        icon: '🍳',
        category: 'Kitchen',
        description: 'Premium 4-burner glass-top gas stove with auto-ignition, heavy-duty pan supports, and toughened glass body.',
        dimensions: { width: '60 cm', depth: '52 cm', height: '8 cm' },
        weight: '8 kg',
        warranty: '2 Years Warranty',
        rating: 4.3,
        reviews: 3200,
        materials: [
            { name: 'Top', detail: '8mm Toughened Glass' },
            { name: 'Burner', detail: 'Forged Brass Burners' },
            { name: 'Support', detail: 'Heavy-Duty Cast Iron Pan Support' },
            { name: 'Knobs', detail: 'Metal with Soft Touch' },
        ],
        priceRange: { min: 3000, max: 25000 },
        variants: [
            { name: '4-Burner Glass', price: 8000, color: '#111' },
            { name: 'Built-in Hob', price: 18000, color: '#333' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'MATMÄSSIG Gas Hob',
                price: '₹14,990',
                url: 'https://www.ikea.com/in/en/cat/hobs-ka004/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Prestige 4 Burner',
                price: '₹5,999',
                url: 'https://www.pepperfry.com/category/gas-stoves.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Faber Cooktop',
                price: '₹9,999',
                url: 'https://www.urbanladder.com/kitchen-appliances',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Kitchen', 'Cooking', 'Gas'],
    },

    desk: {
        label: 'Office Desk',
        icon: '🖥️',
        category: 'Office',
        description: 'Spacious office desk with cable management, built-in drawers, and ergonomic height for productive work sessions.',
        dimensions: { width: '120 cm', depth: '60 cm', height: '75 cm' },
        weight: '25 kg',
        warranty: '3 Years Warranty',
        rating: 4.4,
        reviews: 1340,
        materials: [
            { name: 'Top', detail: 'Engineered Wood (E1 MDF)' },
            { name: 'Frame', detail: 'Powder-Coated Steel' },
            { name: 'Finish', detail: 'Melamine / PU Laminate' },
            { name: 'Edge', detail: 'ABS Edge Banding' },
        ],
        priceRange: { min: 6000, max: 25000 },
        variants: [
            { name: 'White + Oak', price: 10000, color: '#f0ebe0' },
            { name: 'All Black', price: 12000, color: '#222' },
            { name: 'Standing Desk', price: 22000, color: '#555' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'MALM Desk',
                price: '₹9,990',
                url: 'https://www.ikea.com/in/en/cat/desks-for-home-20649/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Helios Study Table',
                price: '₹7,999',
                url: 'https://www.pepperfry.com/category/study-tables.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Graham Study Table',
                price: '₹11,499',
                url: 'https://www.urbanladder.com/study-tables',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Office', 'Study', 'Work From Home'],
    },

    bookshelf: {
        label: 'Bookshelf',
        icon: '📚',
        category: 'Office',
        description: 'Open bookshelf with multiple compartments, ladder design, suitable for books and display items.',
        dimensions: { width: '80 cm', depth: '30 cm', height: '180 cm' },
        weight: '22 kg',
        warranty: '3 Years Warranty',
        rating: 4.3,
        reviews: 780,
        materials: [
            { name: 'Body', detail: 'Engineered Wood / Solid Sheesham' },
            { name: 'Finish', detail: 'Melamine / Natural Oil' },
            { name: 'Brackets', detail: 'Metal L-Brackets (Hidden)' },
        ],
        priceRange: { min: 5000, max: 20000 },
        variants: [
            { name: 'Natural Wood', price: 8000, color: '#8b5a2b' },
            { name: 'White Ladder', price: 6000, color: '#f0f0f0' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'KALLAX Shelf Unit',
                price: '₹7,990',
                url: 'https://www.ikea.com/in/en/cat/bookcases-shelving-units-st002/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Yuko Bookshelf',
                price: '₹5,999',
                url: 'https://www.pepperfry.com/category/bookshelves.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Rhodes Bookshelf',
                price: '₹10,999',
                url: 'https://www.urbanladder.com/book-shelves',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Office', 'Storage', 'Display'],
    },

    officeChair: {
        label: 'Office Chair',
        icon: '🪑',
        category: 'Office',
        description: 'Ergonomic mesh-back office chair with adjustable lumbar support, armrests, and pneumatic height control.',
        dimensions: { width: '65 cm', depth: '65 cm', height: '105-120 cm' },
        weight: '14 kg',
        warranty: '3 Years Warranty',
        rating: 4.5,
        reviews: 4560,
        materials: [
            { name: 'Back', detail: 'Breathable Mesh Fabric' },
            { name: 'Seat', detail: 'Moulded Foam (45D)' },
            { name: 'Frame', detail: 'Nylon / Aluminium Base' },
            { name: 'Casters', detail: 'PU Casters (Floor-Safe)' },
            { name: 'Armrest', detail: '2D / 4D Adjustable' },
        ],
        priceRange: { min: 5000, max: 30000 },
        variants: [
            { name: 'Mesh Black', price: 8000, color: '#222' },
            { name: 'Mesh Grey', price: 8500, color: '#888' },
            { name: 'Premium Leather', price: 25000, color: '#2c1a0e' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'MARKUS Office Chair',
                price: '₹16,990',
                url: 'https://www.ikea.com/in/en/cat/office-chairs-20652/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Helios Ergonomic Chair',
                price: '₹6,999',
                url: 'https://www.pepperfry.com/category/office-chairs.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Venturi Study Chair',
                price: '₹12,999',
                url: 'https://www.urbanladder.com/office-chairs',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Office', 'Ergonomic', 'Seating'],
    },

    plant: {
        label: 'Indoor Plant',
        icon: '🌿',
        category: 'Decor',
        description: 'Live indoor plant in a decorative ceramic pot. Low-maintenance varieties ideal for air purification.',
        dimensions: { width: '30 cm', depth: '30 cm', height: '40-90 cm' },
        weight: '3 kg',
        warranty: 'Replacement if DOA',
        rating: 4.1,
        reviews: 2340,
        materials: [
            { name: 'Pot', detail: 'Ceramic / Fiberglass' },
            { name: 'Plant', detail: 'Money Plant / Snake Plant / Areca Palm' },
            { name: 'Soil', detail: 'Potting Mix with Perlite' },
        ],
        priceRange: { min: 500, max: 5000 },
        variants: [
            { name: 'Snake Plant (Small)', price: 799, color: '#2e7d32' },
            { name: 'Areca Palm (Medium)', price: 1499, color: '#388e3c' },
            { name: 'Fiddle Leaf Fig', price: 2999, color: '#1b5e20' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'FEJKA Artificial Plant',
                price: '₹299',
                url: 'https://www.ikea.com/in/en/cat/plants-pots-stands-pp001/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Ceramic Planter Set',
                price: '₹1,299',
                url: 'https://www.pepperfry.com/category/planters.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Breath Plant Stand',
                price: '₹2,499',
                url: 'https://www.urbanladder.com/planters',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Decor', 'Plant', 'Air Purifier'],
    },

    rug: {
        label: 'Area Rug',
        icon: '🧶',
        category: 'Decor',
        description: 'Hand-tufted area rug with premium wool-blend construction, anti-slip backing, and vibrant colors.',
        dimensions: { width: '200 cm', depth: '300 cm', height: '1.5 cm' },
        weight: '8 kg',
        warranty: '1 Year Warranty',
        rating: 4.2,
        reviews: 560,
        materials: [
            { name: 'Fiber', detail: 'Wool + Polyester Blend' },
            { name: 'Backing', detail: 'Cotton Canvas with Anti-Slip Latex' },
            { name: 'Weave', detail: 'Hand-Tufted / Machine-Woven' },
        ],
        priceRange: { min: 3000, max: 25000 },
        variants: [
            { name: 'Geometric Grey', price: 6000, color: '#888' },
            { name: 'Persian Red', price: 12000, color: '#8b0000' },
            { name: 'Minimalist White', price: 8000, color: '#f0ede8' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'VINDUM High-pile Rug',
                price: '₹12,990',
                url: 'https://www.ikea.com/in/en/cat/rugs-10653/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Athena Area Rug',
                price: '₹4,999',
                url: 'https://www.pepperfry.com/category/rugs-carpets.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Belmonte Rug',
                price: '₹7,999',
                url: 'https://www.urbanladder.com/carpets-rugs',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Decor', 'Floor', 'Carpet'],
    },

    lampFloor: {
        label: 'Floor Lamp',
        icon: '💡',
        category: 'Decor',
        description: 'Minimalist floor standing lamp with adjustable head, warm LED bulb, and sleek metal stand.',
        dimensions: { width: '30 cm', depth: '30 cm', height: '160 cm' },
        weight: '5 kg',
        warranty: '1 Year Warranty',
        rating: 4.3,
        reviews: 890,
        materials: [
            { name: 'Stand', detail: 'Powder-Coated Iron / Brass' },
            { name: 'Shade', detail: 'Fabric / Frosted Glass' },
            { name: 'Bulb', detail: 'E27 LED (Warm White 2700K)' },
            { name: 'Base', detail: 'Weighted Metal Base' },
        ],
        priceRange: { min: 2500, max: 12000 },
        variants: [
            { name: 'Black Metal', price: 4500, color: '#222' },
            { name: 'Gold Brass', price: 7000, color: '#c49a2a' },
            { name: 'Modern Arc', price: 9500, color: '#555' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'HEKTÁR Floor Lamp',
                price: '₹3,990',
                url: 'https://www.ikea.com/in/en/cat/floor-lamps-10731/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Crane Floor Lamp',
                price: '₹3,499',
                url: 'https://www.pepperfry.com/category/floor-lamps.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Darcie Floor Lamp',
                price: '₹5,999',
                url: 'https://www.urbanladder.com/floor-lamps',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Decor', 'Lighting', 'Ambient'],
    },

    window: {
        label: 'Window',
        icon: '🪟',
        category: 'Structure',
        description: 'UPVC double-glazed window unit with sound insulation, weather sealing, and multi-point locking system.',
        dimensions: { width: '120 cm', depth: '8 cm', height: '150 cm' },
        weight: '25 kg',
        warranty: '10 Years Warranty',
        rating: 4.6,
        reviews: 340,
        materials: [
            { name: 'Frame', detail: 'UPVC With Steel Reinforcement' },
            { name: 'Glass', detail: '5mm + 12mm Gap + 5mm (DGU)' },
            { name: 'Hardware', detail: 'Multi-Point Locking (Roto)' },
            { name: 'Seal', detail: 'EPDM Rubber Gasket' },
        ],
        priceRange: { min: 8000, max: 25000 },
        variants: [
            { name: 'White UPVC', price: 12000, color: '#f0f0f0' },
            { name: 'Wood Grain UPVC', price: 15000, color: '#8b5a2b' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'Window Treatment',
                price: '₹Varies',
                url: 'https://www.ikea.com/in/en/cat/curtains-702/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Window Accessories',
                price: '₹Varies',
                url: 'https://www.pepperfry.com/category/window-blinds.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Curtains & Blinds',
                price: '₹Varies',
                url: 'https://www.urbanladder.com/curtains',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Structure', 'Ventilation', 'Natural Light'],
    },

    door: {
        label: 'Door',
        icon: '🚪',
        category: 'Structure',
        description: 'Solid core flush door with premium hardware, suitable for interior/exterior use with termite resistance.',
        dimensions: { width: '91 cm', depth: '4 cm', height: '213 cm' },
        weight: '30 kg',
        warranty: '5 Years Warranty',
        rating: 4.4,
        reviews: 450,
        materials: [
            { name: 'Core', detail: 'Block-Board / Solid Core' },
            { name: 'Surface', detail: 'Natural Veneer / Laminate' },
            { name: 'Hardware', detail: 'SS Mortise Lock + Hinges' },
            { name: 'Treatment', detail: 'Anti-Termite + Waterproof' },
        ],
        priceRange: { min: 4000, max: 20000 },
        variants: [
            { name: 'Teak Veneer', price: 8000, color: '#8b5a2b' },
            { name: 'White Laminate', price: 6000, color: '#f5f5f5' },
            { name: 'Panel Door', price: 12000, color: '#5c3a1e' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'Door Accessories',
                price: '₹Varies',
                url: 'https://www.ikea.com/in/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Door Handles & Locks',
                price: '₹Varies',
                url: 'https://www.pepperfry.com/category/door-handles.html',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Home Hardware',
                price: '₹Varies',
                url: 'https://www.urbanladder.com/',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Structure', 'Door', 'Hardware'],
    },

    duck: {
        label: 'Rubber Duck',
        icon: '🦆',
        category: 'Decor',
        description: 'Classic rubber duck — the ultimate desk companion and debugging assistant. Adds instant joy to any space.',
        dimensions: { width: '8 cm', depth: '8 cm', height: '8 cm' },
        weight: '0.05 kg',
        warranty: 'Lifetime Smiles',
        rating: 5.0,
        reviews: 9999,
        materials: [
            { name: 'Body', detail: 'BPA-Free PVC / Natural Rubber' },
            { name: 'Paint', detail: 'Non-Toxic Water-Based' },
        ],
        priceRange: { min: 99, max: 499 },
        variants: [
            { name: 'Classic Yellow', price: 199, color: '#fdd835' },
            { name: 'Devil Duck', price: 299, color: '#e53935' },
        ],
        buyLinks: [
            {
                store: 'IKEA',
                name: 'Bath Toys',
                price: '₹199',
                url: 'https://www.ikea.com/in/en/',
                logo: '🔵',
                color: '#0051ba',
            },
            {
                store: 'Pepperfry',
                name: 'Decorative Ducks',
                price: '₹149',
                url: 'https://www.pepperfry.com/',
                logo: '🟠',
                color: '#e65100',
            },
            {
                store: 'Urban Ladder',
                name: 'Quirky Decor',
                price: '₹249',
                url: 'https://www.urbanladder.com/',
                logo: '🟡',
                color: '#ff9800',
            },
        ],
        tags: ['Decor', 'Fun', 'Debugging'],
    },
};

/**
 * Get catalog data for a furniture type.
 * Returns null if not found.
 */
export function getCatalogItem(type) {
    return FURNITURE_CATALOG[type] || null;
}

/**
 * Get all catalog items.
 */
export function getAllCatalogItems() {
    return FURNITURE_CATALOG;
}

/**
 * Render star rating as a string of ★ and ☆
 */
export function renderStars(rating) {
    const full = Math.floor(rating);
    const half = rating % 1 >= 0.5 ? 1 : 0;
    const empty = 5 - full - half;
    return '★'.repeat(full) + (half ? '½' : '') + '☆'.repeat(empty);
}

export default FURNITURE_CATALOG;
